let THREE;try{THREE=await import('https://cdn.jsdelivr.net/npm/three@0.186.0/build/three.module.js')}catch(e){const h=document.getElementById('world-canvas');if(h)h.innerHTML='<div class="world-noscript">The 3D engine could not load. <a href="work.html">Open the standard portfolio</a>.</div>';throw e}
const host=document.getElementById('world-canvas'),nameEl=document.getElementById('world-selected-name'),copyEl=document.getElementById('world-selected-copy'),metaEl=document.getElementById('world-selected-meta');
const reduced=matchMedia('(prefers-reduced-motion:reduce)').matches,mobile=matchMedia('(max-width:720px)').matches;
const items=[['DeepSeek','logos/Deepseek%20logo.jpg','AI / GENAI','Local and open model exploration.','cube'],['Claude','logos/claude.jpg','AI / GENAI','AI assistant and model ecosystem.','sphere'],['GitHub Copilot','logos/copilot.png','ENGINEERING','AI-assisted software development.','octa'],['Antigravity','logos/Antigravity.jpg','AI / TOOLS','Experimental AI tooling.','torus'],['Nmap','logos/nmap.jpg','SECURITY','Network discovery and scanning.','cube'],['Burp Suite','logos/burpsuite.jpg','SECURITY','Web security testing.','sphere'],['Kali Linux','logos/kali.jpg','SECURITY','Security-focused operating system.','octa'],['Metasploit','logos/metasploit.jpg','SECURITY','Exploit development and research.','cube'],['Gobuster','logos/Gobuster.jpg','SECURITY','Content and directory discovery.','torus'],['FFUF','logos/fuzz.jpg','SECURITY','Fast web fuzzing and endpoint discovery.','sphere'],['Cisco C Essentials','logos/certifications/cisco-c-essentials-1.png','CREDENTIAL','Cisco programming fundamentals.','cube'],['Cisco Ethical Hacker','logos/certifications/cisco-ethical-hacker.png','CREDENTIAL','Cisco ethical hacking credential.','octa'],['Cisco Intro to Cybersecurity','logos/certifications/cisco-introduction-to-cybersecurity.png','CREDENTIAL','Cybersecurity foundations credential.','sphere'],['IBM Cybersecurity Fundamentals','logos/certifications/ibm-cybersecurity-fundamentals.png','CREDENTIAL','IBM cybersecurity foundation.','cube'],['ISC2 Candidate','logos/certifications/isc2-candidate.png','CREDENTIAL','ISC2 candidate credential record.','torus'],['MongoDB CRUD Operations','logos/certifications/mongodb-crud-operations.png','CREDENTIAL','MongoDB database operations.','sphere'],['Red Hat Python','logos/certifications/redhat-python-programming.png','CREDENTIAL','Red Hat Python programming.','cube'],['Red Hat Linux','logos/certifications/redhat-getting-started-linux.png','CREDENTIAL','Red Hat Linux learning record.','octa']];
const concepts=[['RAG / LLM','AI SYSTEMS','Retrieval, local models and grounded generation.'],['Ollama','AI SYSTEMS','Local LLM runtime and inference.'],['FastAPI','ENGINEERING','Python APIs and services.'],['MCP / Tools','AI SYSTEMS','Tool use and agent-oriented systems.'],['PyTorch','ENGINEERING','Neural networks and training.'],['Docker','ENGINEERING','Containerized development and deployment.'],['Python','ENGINEERING','Primary programming language.'],['GPU','INFRASTRUCTURE','Accelerated model workloads.']];
let renderer;try{renderer=new THREE.WebGLRenderer({antialias:!mobile,alpha:true,powerPreference:'high-performance'})}catch(e){host.innerHTML='<div class="world-noscript">WebGL is unavailable on this device. <a href="work.html">Open the standard portfolio</a>.</div>';throw e}
const cap=mobile?1.25:1.6;renderer.setPixelRatio(Math.min(devicePixelRatio||1,cap));renderer.setSize(host.clientWidth,host.clientHeight,false);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;host.appendChild(renderer.domElement);
const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x090a11,.035);const camera=new THREE.PerspectiveCamera(44,host.clientWidth/Math.max(1,host.clientHeight),.1,100);camera.position.z=13;
const world=new THREE.Group(),layer=new THREE.Group();world.add(layer);scene.add(world);scene.add(new THREE.HemisphereLight(0xc7c3ff,0x0b1118,2.1));
const key=new THREE.DirectionalLight(0xffffff,2.8);key.position.set(4,7,8);scene.add(key);const lilac=new THREE.PointLight(0x8f7cf6,18,28,2);lilac.position.set(-7,1,4);scene.add(lilac);const mint=new THREE.PointLight(0x73c7b3,14,24,2);mint.position.set(7,-4,0);scene.add(mint);
const core=new THREE.Group();core.add(new THREE.Mesh(new THREE.IcosahedronGeometry(1.6,2),new THREE.MeshPhysicalMaterial({color:0x9182f5,roughness:.24,metalness:.45,clearcoat:.7,emissive:0x1b1631,emissiveIntensity:.6})));
[1.95,2.35,2.8].forEach((r,i)=>{const q=new THREE.Mesh(new THREE.TorusGeometry(r,.015+i*.004,8,96),new THREE.MeshBasicMaterial({color:0xb7a9ff,transparent:true,opacity:.27-i*.05}));q.rotation.set(.9+i*.35,.3+i*.45,i*.28);core.add(q)});
const tc=document.createElement('canvas');tc.width=512;tc.height=256;const ctx=tc.getContext('2d');ctx.font='700 64px Inter,Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle='#fff';ctx.fillText('MY WORLD',256,96);ctx.font='600 23px monospace';ctx.fillStyle='rgba(255,255,255,.62)';ctx.fillText('AI · ENGINEERING · SECURITY',256,154);const tt=new THREE.CanvasTexture(tc);tt.colorSpace=THREE.SRGBColorSpace;const label=new THREE.Sprite(new THREE.SpriteMaterial({map:tt,transparent:true,depthWrite:false}));label.scale.set(4.6,2.3,1);core.add(label);layer.add(core);
const starCount=mobile?90:160,pos=new Float32Array(starCount*3);for(let i=0;i<starCount;i++){const r=11+Math.random()*9,a=Math.random()*Math.PI*2,b=Math.acos(Math.random()*2-1);pos[i*3]=Math.sin(b)*Math.cos(a)*r;pos[i*3+1]=Math.sin(b)*Math.sin(a)*r;pos[i*3+2]=Math.cos(b)*r}const sg=new THREE.BufferGeometry();sg.setAttribute('position',new THREE.BufferAttribute(pos,3));const stars=new THREE.Points(sg,new THREE.PointsMaterial({color:0xa9a0ec,size:mobile?.055:.075,transparent:true,opacity:.42}));scene.add(stars);
const colors={'AI / GENAI':0x9f91f4,'AI / TOOLS':0xc2b8ff,'SECURITY':0x76cdb8,'CREDENTIAL':0xf1b79b,'AI SYSTEMS':0xa795ff,'ENGINEERING':0x8fbff1,'INFRASTRUCTURE':0xf0ae92},load=new THREE.TextureLoader(),nodes=[],lines=[];
function tex(url){const t=load.load(url);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=Math.min(renderer.capabilities.getMaxAnisotropy(),4);return t}
function shape(type,s){if(type==='sphere')return new THREE.SphereGeometry(s,20,16);if(type==='octa')return new THREE.OctahedronGeometry(s,1);if(type==='torus')return new THREE.TorusGeometry(s*.78,s*.18,12,40);return new THREE.BoxGeometry(s*1.55,s*1.55,s*1.2)}
function textTex(text){const c=document.createElement('canvas');c.width=512;c.height=160;const x=c.getContext('2d');x.font='700 56px Inter,Arial';x.textAlign='center';x.textBaseline='middle';x.fillStyle='#fff';x.fillText(text,256,78);x.font='600 18px monospace';x.fillStyle='rgba(255,255,255,.45)';x.fillText('3D NODE',256,122);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
function addLogo(item,i){const [n,f,c,d,type]=item,theta=i/items.length*Math.PI*2,phi=Math.acos(1-2*(i+.5)/items.length),r=5.1+(i%3)*.48,g=new THREE.Group(),s=.62+(i%4)*.045,col=colors[c]||0xffffff;g.position.set(Math.sin(phi)*Math.cos(theta)*r,Math.cos(phi)*r*.86,Math.sin(phi)*Math.sin(theta)*r);const base=g.position.clone(),logo=tex(f),side=new THREE.MeshStandardMaterial({color:col,roughness:.34,metalness:.3}),lm=new THREE.MeshStandardMaterial({map:logo,roughness:.25}),m=new THREE.Mesh(shape(type,s),type==='cube'?[side,side,side,side,lm,lm]:new THREE.MeshStandardMaterial({color:col,roughness:.24,metalness:.4,emissive:col,emissiveIntensity:.08}));g.add(m);if(type!=='cube'){const p=new THREE.Mesh(new THREE.PlaneGeometry(s*.95,s*.95),new THREE.MeshBasicMaterial({map:logo,transparent:true,depthWrite:false,side:THREE.DoubleSide}));p.position.z=s*.95;g.add(p)}g.userData={name:n,cat:c,desc:d,base,hover:0,phase:i*.77};layer.add(g);nodes.push(g);const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(),base.clone()]),new THREE.LineBasicMaterial({color:0x8d84bf,transparent:true,opacity:.14}));layer.add(line);lines.push({line,node:g})}
items.forEach(addLogo);
concepts.forEach((it,i)=>{const [n,c,d]=it,a=i/concepts.length*Math.PI*2+.22,r=7.2,g=new THREE.Group();g.position.set(Math.cos(a)*r,Math.sin(a*1.8)*1.8,Math.sin(a)*r);g.userData={name:n,cat:c,desc:d,base:g.position.clone(),hover:0,phase:(items.length+i)*.77};const col=colors[c]||0xffffff;g.add(new THREE.Mesh(new THREE.OctahedronGeometry(.55,1),new THREE.MeshPhysicalMaterial({color:col,roughness:.2,metalness:.6,clearcoat:.8})));const sp=new THREE.Sprite(new THREE.SpriteMaterial({map:textTex(n),transparent:true,depthWrite:false}));sp.scale.set(2.1,.66,1);sp.position.y=-.86;g.add(sp);layer.add(g);nodes.push(g)});
function show(n){if(!n){nameEl.textContent='GN CORE';copyEl.textContent='AI systems, full-stack engineering, security and research — the connected pieces of my work.';metaEl.textContent='CORE · PALADUGU GANESH NAIDU';return}nameEl.textContent=n.userData.name;copyEl.textContent=n.userData.desc;metaEl.textContent=n.userData.cat+' · MY WORLD'}show();
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2(99,99);let hovered=null;function pick(x,y){const r=renderer.domElement.getBoundingClientRect();pointer.x=(x-r.left)/r.width*2-1;pointer.y=-(y-r.top)/r.height*2+1}function hover(){ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(nodes,true)[0];let n=null;if(hit){n=hit.object;while(n&&!n.userData.name)n=n.parent}if(n!==hovered){hovered=n;show(n);renderer.domElement.style.cursor=n?'pointer':'grab'}}
let drag=false,moved=false,lx=0,ly=0,trX=-.08,trY=.16,crX=trX,crY=trY,tz=13,cz=13,pageScroll=0;
renderer.domElement.addEventListener('pointerdown',e=>{drag=true;moved=false;lx=e.clientX;ly=e.clientY;renderer.domElement.setPointerCapture?.(e.pointerId)},{passive:true});
renderer.domElement.addEventListener('pointermove',e=>{pick(e.clientX,e.clientY);if(!drag)return;const dx=e.clientX-lx,dy=e.clientY-ly;if(Math.abs(dx)+Math.abs(dy)>3)moved=true;trY+=dx*.0042;trX=Math.max(-.85,Math.min(.85,trX+dy*.0035));lx=e.clientX;ly=e.clientY},{passive:true});
renderer.domElement.addEventListener('pointerup',e=>{drag=false;renderer.domElement.releasePointerCapture?.(e.pointerId);if(!moved)hover()},{passive:true});
renderer.domElement.addEventListener('pointercancel',()=>drag=false,{passive:true});renderer.domElement.addEventListener('pointerleave',()=>{if(!drag)pointer.set(99,99)},{passive:true});renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();tz=Math.max(8,Math.min(18,tz+e.deltaY*.012))},{passive:false});renderer.domElement.addEventListener('dblclick',()=>{trX=-.08;trY=.16;tz=13});
window.addEventListener('scroll',()=>pageScroll=scrollY||0,{passive:true});window.addEventListener('resize',()=>{const w=host.clientWidth,h=host.clientHeight;camera.aspect=w/Math.max(1,h);camera.updateProjectionMatrix();renderer.setPixelRatio(Math.min(devicePixelRatio||1,cap));renderer.setSize(w,h,false)},{passive:true});
const clock=new THREE.Clock();function animate(){const t=clock.getElapsedTime(),p=Math.max(0,Math.min(1,pageScroll/Math.max(1,host.clientHeight)));crX+=(trX-p*.38-crX)*(reduced?.035:.08);crY+=(trY+p*.55-crY)*(reduced?.035:.08);cz+=(tz-p*.9-cz)*(reduced?.06:.09);world.rotation.x=crX;world.rotation.y=crY;camera.position.z=cz;camera.lookAt(0,0,0);if(!reduced){core.rotation.y=t*.18;stars.rotation.y=t*.015}nodes.forEach(n=>{const u=n.userData;u.hover+=(hovered===n?1:0-u.hover)*.12;n.scale.setScalar(1+(reduced?0:Math.sin(t*.9+u.phase)*.03)+u.hover*.28);n.position.x=u.base.x;n.position.y=u.base.y+(reduced?0:Math.sin(t*.7+u.phase)*.06);n.position.z=u.base.z;n.rotation.x+=reduced?0:.0017;n.rotation.y+=reduced?0:.0022});lines.forEach(q=>{const a=q.line.geometry.attributes.position.array;a[3]=q.node.position.x;a[4]=q.node.position.y;a[5]=q.node.position.z;q.line.geometry.attributes.position.needsUpdate=true});hover();renderer.render(scene,camera)}renderer.setAnimationLoop(animate);document.addEventListener('visibilitychange',()=>renderer.setAnimationLoop(document.hidden?null:animate));
