import milestones from '../data/milestones.json';
const host=document.querySelector('#journey-space');let selectVisual=()=>{};
function select(i){const m=milestones[i];document.querySelector('#space-year').textContent=m.year;document.querySelector('#space-title').textContent=m.title;document.querySelector('#space-text').textContent=m.text;document.querySelector('#space-link').href=m.href;document.querySelectorAll('[data-milestone]').forEach(b=>{const yes=Number(b.dataset.milestone)===i;b.classList.toggle('selected',yes);b.setAttribute('aria-pressed',String(yes))});selectVisual(i)}
document.querySelectorAll('[data-milestone]').forEach(b=>b.addEventListener('click',()=>select(Number(b.dataset.milestone))));
if(host){(async()=>{let THREE,OrbitControls;try{THREE=await import('three');({OrbitControls}=await import('three/addons/controls/OrbitControls.js'))}catch{return}let renderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'low-power'})}catch{return}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.domElement.setAttribute('aria-hidden','true');host.prepend(renderer.domElement);host.classList.add('space-ready');const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(45,1,.1,100);camera.position.set(0,3,14);scene.add(new THREE.HemisphereLight(0xf4f6ff,0x6e887b,3));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(3,7,8);scene.add(light);const group=new THREE.Group();scene.add(group);const colors=[0xbdd4bc,0xddccef,0xe9c9b0,0xb7d4e8];const nodes=[];
const stars=new Float32Array(900*3);for(let i=0;i<stars.length;i++)stars[i]=(Math.sin(i*83.1)*43758.55%1)*36;const sg=new THREE.BufferGeometry();sg.setAttribute('position',new THREE.BufferAttribute(stars,3));scene.add(new THREE.Points(sg,new THREE.PointsMaterial({size:.035,color:0xdde5dd,transparent:true,opacity:.6})));
const center=new THREE.Mesh(new THREE.IcosahedronGeometry(.75,2),new THREE.MeshStandardMaterial({color:0xb9c9ac,metalness:.3,roughness:.4}));group.add(center);
function label(text){const c=document.createElement('canvas');c.width=512;c.height=96;const ctx=c.getContext('2d');ctx.font='500 30px sans-serif';ctx.textAlign='center';ctx.fillStyle='#f0f3ed';ctx.fillText(text,256,59);const tx=new THREE.CanvasTexture(c);tx.colorSpace=THREE.SRGBColorSpace;const sp=new THREE.Sprite(new THREE.SpriteMaterial({map:tx,transparent:true,depthTest:false}));sp.scale.set(2.5,.47,1);return sp}
const positions=milestones.map((_,i)=>{const a=i/milestones.length*Math.PI*2;return new THREE.Vector3(Math.cos(a)*(3.6+i%2),Math.sin(a)*2.4,(i%3-1)*1.8)});
for(let i=0;i<milestones.length;i++){const node=new THREE.Mesh(new THREE.SphereGeometry(.32,24,16),new THREE.MeshStandardMaterial({color:colors[i%4],roughness:.45,metalness:.1}));node.position.copy(positions[i]);node.userData.index=i;group.add(node);nodes.push(node);const sp=label(milestones[i].title);sp.position.copy(node.position);sp.position.y-=.62;group.add(sp);const geom=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(),node.position]);group.add(new THREE.Line(geom,new THREE.LineBasicMaterial({color:0xa8bda7,transparent:true,opacity:.22})));}
const halo=new THREE.Mesh(new THREE.TorusGeometry(.49,.025,8,48),new THREE.MeshBasicMaterial({color:0xebf2dc}));group.add(halo);selectVisual=i=>{halo.position.copy(nodes[i].position);nodes.forEach((n,j)=>n.scale.setScalar(j===i?1.25:1));render()};selectVisual(0);
const controls=new OrbitControls(camera,renderer.domElement);controls.enablePan=false;controls.enableDamping=false;controls.minDistance=8;controls.maxDistance=23;controls.maxPolarAngle=Math.PI*.85;controls.addEventListener('change',()=>render());let raf=0,last=0,inView=true;const reduced=matchMedia('(prefers-reduced-motion: reduce)');const stopped=()=>reduced.matches||document.body.classList.contains('motion-paused')||document.hidden||!inView;
function render(){renderer.render(scene,camera)}function frame(t){raf=0;if(stopped())return;if(t-last>=33){center.rotation.y+=.004;halo.rotation.z+=.008;last=t;render()}raf=requestAnimationFrame(frame)}function resume(){if(raf)cancelAnimationFrame(raf);render();if(!stopped())raf=requestAnimationFrame(frame)}function resize(){const r=host.getBoundingClientRect();renderer.setSize(r.width,r.height);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();render()}
new ResizeObserver(resize).observe(host);new IntersectionObserver(e=>{inView=e[0].isIntersecting;resume()}).observe(host);document.addEventListener('motionchange',resume);document.addEventListener('visibilitychange',resume);reduced.addEventListener('change',resume);
const pointer=new THREE.Vector2(),ray=new THREE.Raycaster();let down={x:0,y:0};renderer.domElement.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY}});renderer.domElement.addEventListener('pointerup',e=>{if(Math.hypot(e.clientX-down.x,e.clientY-down.y)>8)return;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(nodes)[0];if(hit)select(hit.object.userData.index)});resize();resume();})().catch(()=>host.classList.remove('space-ready'));}
